spring:
  datasource:
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234springbootvsmybatis
    driver-class-name: com.mysql.cj.jdbc.Driver